# Generated by Django 5.2.8 on 2025-12-01 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cuenta', models.CharField(max_length=50, unique=True)),
                ('nombre_cuenta', models.CharField(max_length=200)),
                ('presupuesto_inicial', models.DecimalField(decimal_places=0, max_digits=12)),
                ('modificaciones', models.DecimalField(decimal_places=0, max_digits=12)),
                ('presupuesto_vigente', models.DecimalField(decimal_places=0, max_digits=12)),
                ('porcentaje_ejecucion', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=20, unique=True)),
                ('project_id', models.CharField(max_length=20)),
                ('nombre_actividad', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado'), ('Atrasado', 'Atrasado')], default='Pendiente', max_length=20)),
                ('responsable', models.CharField(max_length=100)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
