# Generated by Django 5.2.8 on 2025-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_municipal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentapresupuestaria',
            name='modificaciones',
        ),
        migrations.RemoveField(
            model_name='cuentapresupuestaria',
            name='porcentaje_ejecucion',
        ),
        migrations.RemoveField(
            model_name='cuentapresupuestaria',
            name='presupuesto_inicial',
        ),
        migrations.AlterField(
            model_name='actividadproyecto',
            name='activity_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID Actividad'),
        ),
        migrations.AlterField(
            model_name='actividadproyecto',
            name='project_id',
            field=models.CharField(max_length=20, verbose_name='ID Proyecto'),
        ),
        migrations.AlterField(
            model_name='actividadproyecto',
            name='responsable',
            field=models.CharField(choices=[('SECPLAN', 'Secretaría Comunal de Planificación'), ('DIDECO', 'Desarrollo Comunitario'), ('DOM', 'Dirección de Obras'), ('TRANSITO', 'Dirección de Tránsito'), ('ALCALDIA', 'Gabinete Alcaldía')], default='SECPLAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentapresupuestaria',
            name='codigo_cuenta',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código Presupuestario'),
        ),
    ]
