# Generated by Django 5.2.8 on 2025-12-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_municipal', '0002_remove_cuentapresupuestaria_modificaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentapresupuestaria',
            name='modificaciones',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Modificaciones Actuales'),
        ),
        migrations.AddField(
            model_name='cuentapresupuestaria',
            name='presupuesto_inicial',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Presupuesto Inicial'),
        ),
        migrations.AlterField(
            model_name='cuentapresupuestaria',
            name='nombre_cuenta',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuentapresupuestaria',
            name='presupuesto_vigente',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Presupuesto Final Vigente'),
        ),
    ]
